services:
  llama-server:
    build: .
    image: localhost/rocm_llamacpp:latest
    container_name: rocm_llamacpp
    ports:
      - "8080:8080"
    networks:
      - webui-net
    ipc: host
    privileged: true
    devices:
      - "/dev/kfd:/dev/kfd"
      - "/dev/dri:/dev/dri"
    security_opt:
      - label=disable
      - seccomp=unconfined
    volumes:
      - gguf_models:/root/.cache/huggingface/hub
      - ./config.yaml:/workspace/config.yaml:ro
    environment:
      - HIP_VISIBLE_DEVICES=0
    command: ["--config", "/workspace/config.yaml", "--listen", "0.0.0.0:8080"]
    stdin_open: true
    tty: true

  download-model:
    image: localhost/rocm_llamacpp:latest
    container_name: rocm_downloader
    network_mode: host
    volumes:
      - gguf_models:/root/.cache/huggingface/hub
    environment:
      - HF_TOKEN
    entrypoint: ["hf", "download"]
    command: []
    # 'profiles' prevents this container from starting when you run 'podman-compose up'
    profiles:
      - tools

volumes:
  gguf_models:
    external: true

networks:
  webui-net:
    external: true
