globalTTL: 300
startPort: 8090
logToStdout: "both"

macros:
  "llama-server": >
    /workspace/llama.cpp/build/bin/llama-server
    --port ${PORT}
    -lv 3
    --host 127.0.0.1
    -fa on
    -t 14
    --no-mmap
    --spec-type ngram-mod
    --no-warmup
    --fit-target 512
    --fit-ctx 12000

models:
  "gemma-4-26B-A4B":
    cmd: >
      ${llama-server}
      -hf TrevorJS/gemma-4-26B-A4B-it-uncensored-GGUF
      -c 65536

  "gemma-4-31B":
    cmd: >
      ${llama-server}
      -hf llmfan46/gemma-4-31B-it-uncensored-heretic-GGUF

  "qwable-3.6-35B":
    cmd: >
      ${llama-server}
      -hf Mia-AiLab/Qwable-3.6-35b:q8_0
      --cpu-moe
      -c 131072

  "ornith-1.0-35B":
    cmd: >
      ${llama-server}
      -hf deepreinforce-ai/Ornith-1.0-35B-GGUF:Q8_0
      --cpu-moe
      -c 131072

  "ternary-bonsai-27B":
    cmd: >
      ${llama-server}
      -hf prism-ml/Ternary-Bonsai-27B-gguf
      -c 65536

  "qwen3-4B-slow":
    cmd: >
      ${llama-server}
      --device none
      -hf unsloth/Qwen3-4B-GGUF
      --no-mmproj
      --reasoning off
      -c 32768
    ttl: 900

  "qwen3-4B-fast":
    cmd: >
      ${llama-server}
      -hf unsloth/Qwen3-4B-GGUF
      --no-mmproj
      -c 32768
    ttl: 900


matrix:
  vars:
    qs: qwen3-4B-slow
    qf: qwen3-4B-fast
    gem426: gemma-4-26B-A4B
    gem431: gemma-4-31B
    qwable: qwable-3.6-35B
    ornith: ornith-1.0-35B
    bonsai: ternary-bonsai-27B

  sets:
    qwen3fast_with_qwen3_4b: "qs & qf"
    gemma_26B_with_qwen3_4b: "gem426 & qs"
    gemma_31B_with_qwen3_4b: "gem431 & qs"
    qwable_qwen3_4b: "qwable & qs"
    ornith_with_qwen3_4b: "ornith & qs"
    bonsai_with_qwen3_4b: "bonsai & qs"
