globalTTL: 300
startPort: 8081
logToStdout: "both"

macros:
  "llama-server": >
    /workspace/llama.cpp/build/bin/llama-server
    --port ${PORT}
    -lv 3
    --host 127.0.0.1
    -fa on
    -t 14
    --no-mmap
    --spec-type ngram-mod
    --no-warmup
    --fit-target 2048
    --fit-ctx 12000

models:
  "Qwen-Coder-Next":
    cmd: >
      ${llama-server}
      -hf unsloth/Qwen3-Coder-Next-GGUF
      -c 65536
      --cpu-moe

  "GLM-4.7-Flash":
    cmd: >
      ${llama-server}
      -hf mradermacher/GLM-4.7-Flash-heretic-1.2.0-GGUF:Q8_0
      --cpu-moe

  "GLM-Steam-106B":
    cmd: >
      ${llama-server}
      -hf bartowski/TheDrummer_GLM-Steam-106B-A12B-v1-GGUF:Q2_K
      --cpu-moe

  "gemma-4-26B":
    cmd: >
      ${llama-server}
      -hf mradermacher/gemma-4-26B-A4B-it-abliterix-i1-GGUF
      -c 65536

  "gemma-4-31B-uncensored":
    cmd: >
      ${llama-server}
      -hf llmfan46/gemma-4-31B-it-uncensored-heretic-GGUF

  "Qwen3-4B":
    cmd: >
      ${llama-server}
      --device none
      -hf unsloth/Qwen3-4B-GGUF
      --no-mmproj
      --reasoning off
      -c 32768
    ttl: 900

matrix:
  vars:
    q: Qwen3-4B
    qwecd: Qwen-Coder-Next
    glmfl: GLM-4.7-Flash
    glmstm: GLM-Steam-106B
    gem426: gemma-4-26B
    gem431: gemma-4-31B-uncensored

  sets:
    qwen_coder_with_qwen3_4b: "qwecd & q"
    glm_flash_with_qwen3_4b: "glmfl & q"
    glm_steam_with_qwen3_4b: "glmstm & q"
    gemma_26B_with_qwen3_4b: "gem426 & q"
    gemma_31B_with_qwen3_4b: "gem431 & q"
